---
- name: Cisco Gather facts
  hosts: Silentguy-1
  connection: local
  gather_facts: no
  
  tasks:
    - name: Get Facts on Cisco 
      cisco.ios.ios_facts:
        gather_subset: config
#        gather_network_resources: l3_interfaces
     
      register: cisco_facts
    
    - name: print the facts
      debug: 
        msg: "{{ cisco_facts }}"
        
