---
- name: config gen using Jinja2 Template
  hosts: [firewalls]
  roles: [Juniper.junos]
  connection: local
  gather_facts: no

  vars:
    tmp_dir: "{{user_data_path}}/tmp"
    config_file: "{{tmp_dir}}/{{inventory_hostname}}.conf"
    #connection_settings:

  tasks:
#    - debug: var=tmp_dir
#    - debug: var=config_file
    
    - name: Confirm if TMP dir in place
      file:
        path: "{{tmp_dir}}"
        state: 'directory'
      run_once: yes
      delegate_to: 'localhost'

    - name: Generate the config file
      template:                             #module tells Ansible to parse a Jinja2 file
        src: "template/base-settings.j2"
        dest: "{{config_file}}"
