---
- name: Play - Retrieve interface configuration
  hosts: firewalls
  roles: 
    - Juniper.junos
  connection: local
  gather_facts: no
  
#uncoment if no host-vars or group-vars passwd and user are not used
#  vars_prompt:
#   - name: USERNAME
#     prompt: User name
#     private: no 
#   - name: DEVICE_PASSWORD
#     prompt: Device password
#     private: yes

  tasks:
    - name: Retrieve committed configuration of the interfaces
      juniper_junos_config: #https://junos-ansible-modules.readthedocs.io/en/2.4.0/juniper_junos_config.html
#        user: "{{ USERNAME }}"
#        passwd: "{{ DEVICE_PASSWORD }}"
        retrieve: committed  #commited == active or running
        filter: policy-options/policy-statement/name

      register: response
                
 
    - name: Print the the config lines
      debug: #var=response.config_lines -- allowed too
        var: response.config_lines      #var is not "{{}}". why not msg? because msg shows system messages for this module, in other words is operational not config 
