---
- name: Retrieve device configuration
  hosts: firewalls
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Retrieve the committed configuration
      juniper_junos_config:
        retrieve: committed  #commited == active or running
        diff: false
        check: false
        commit: false
        filter: 'system/ntp'

      register: response

    - name: Print the lines in the config.
      debug:
        var: response.config_lines
